package layout

type SchemasLayout struct {
	workspace WorkspaceLayout
	path      WorkspaceFolder
}

func (wl WorkspaceLayout) Schemas() SchemasLayout {
	return SchemasLayout{
		workspace: wl,
		path:      wl.path.append("schemas"),
	}
}

func (sl SchemasLayout) Mify() WorkspaceFile {
	return sl.path.file("service.mify.yaml")
}

// Schema used for mify-cloud integration
func (sl SchemasLayout) Cloud() WorkspaceFile {
	return sl.path.file("cloud.mify.yaml")
}

// Folder where all api (for now it is openapi) schemas for specified service are located
func (sl SchemasLayout) ApiRoot(serviceName string) WorkspaceFolder {
	return sl.path.append(serviceName, "api")
}

// This method returns path to api schema with specific name for specific service.
// Each service can have multiple api schemas (at least user defined + mify generated, but not limited to them).
func (sl SchemasLayout) ApiSchema(serviceName string, schemaName string) WorkspaceFolder {
	return sl.path.append(serviceName, "api", schemaName)
}

// Path to api_generated.yaml (this part of api schema is generated by mify itself)
func (sl SchemasLayout) ApiSchemaGenerated(serviceName string, schemaName string) WorkspaceFile {
	return sl.path.append(serviceName, "api").file("api_generated.yaml")
}
