generatorName: javascript
templateDir: /repo/.mify/assets/openapi/client-template/js
enableMinimalUpdate: true
globalProperties:
  apiTests: false
  modelTests: false
  apiDocs: false
  modelDocs: false
additionalProperties:
  usePromises: true
  packageName: openapi
files:
  ignore-list.txt:
    destinationFilename: .openapi-generator-ignore

releaseNote: Release note
httpUserAgent: User Agent

apiPackage: handlers
modelPackage: models
invokerPackage: null
sourceFolder: null

apiNameSuffix: "_"
modelNamePrefix: ""
modelNameSuffix: ""
library: ""

instantiationTypes: {}
typeMappings: {}
importMappings: {}
languageSpecificPrimitives: []
reservedWordMappings: {}
serverVariables: {}

verbose: false
skipOverwrite: false
removeOperationIdPrefix: false
skipOperationExample: false
logToStderr: false
validateSpec: true
enablePostProcessFile: false
strictSpecBehavior: true
generateAliasAsModel: false
templatingEngineName: mustache
